name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Backend
      env: 
        deploy_url: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl "$deploy_url"
    - name: Deploy Frontend
      env:
        deploy_url: ${{ secrets.RENDER_CLIENT_KEY }}
      run: |
        curl "$deploy_url"
