name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      env: 
        deploy_url: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl "$deploy_url"
